name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install server deps
        working-directory: server
        run: |
          npm ci
          node -v

      - name: Start API (background)
        working-directory: server
        env:
          MONGO_URL: mongodb://localhost:27017/daipay
        run: |
          nohup npm start &
          sleep 3

      - name: Smoke request (should 404 wallets list if not implemented)
        run: |
          curl -sS http://localhost:8080/v1/blocks || true

      - name: Install web deps
        working-directory: web
        run: npm ci

      - name: Build web
        working-directory: web
        run: npm run build
